### PR TITLE
Devices management

### LINKED ISSUE #37: Devices management

### PR DESCRIPTION
**Pull request by gjuchault**
Fixes #37

### CODE REVIEW

**Comment by gjuchault** [comment]
Missing :

- [ ] Lint
- [ ] Checkboxes in tables

**Comment by lonk** [comment]
It doesn't work properly because the bugfix on fetch isn't deployed in this branch, but it will be okay after merging.

**Comment by lonk** [comment]
Now it's good :3

**Comment by lonk** [comment]
Good job, lonk.

**Pull request merged**
